name: CI Matrix Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: linux-x86_64
            runs-on: ubuntu-latest
          - name: linux-arm64
            runs-on: ubuntu-24.04-arm
          - name: macos-arm64
            runs-on: macos-latest
          - name: macos-x86_64
            runs-on: macos-13
          # - name: windows-x86_64
          #   runs-on: windows-latest

    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4

      - name: Install libopenblas-dev (Linux ARM64 only)
        if: matrix.name == 'linux-arm64'
        run: |
          sudo apt-get update
          sudo apt-get install -y libopenblas-dev

      - name: Install dependencies (Linux x86_64 only)
        if: matrix.name == 'linux-x86_64'
        run: |
          wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB \
          | gpg --dearmor | sudo tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null

          # add signed entry to apt sources and configure the APT client to use Intel repository:
          echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list

          sudo apt install build-essential gcc dirmngr ca-certificates software-properties-common apt-transport-https dkms curl -y
          curl -fSsL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/3bf863cc.pub | sudo gpg --dearmor | sudo tee /usr/share/keyrings/nvidia-drivers.gpg > /dev/null 2>&1
          echo 'deb [signed-by=/usr/share/keyrings/nvidia-drivers.gpg] https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/ /' | sudo tee /etc/apt/sources.list.d/nvidia-drivers.list
          sudo apt update
          sudo apt install nvidia-driver-535 cuda-drivers-535 cuda
          sudo apt install intel-basekit
          sudo apt install intel-oneapi-dnnl-devel
          sudo apt install openmpi-bin libopenmpi-dev

      - name: Install dependencies (macOS x86_64 only)
        if: matrix.name == 'macos-x86_64'
        run: |
          ONEAPI_INSTALLER_URL=https://registrationcenter-download.intel.com/akdlm/IRC_NAS/cd013e6c-49c4-488b-8b86-25df6693a9b7/m_BaseKit_p_2023.2.0.49398.dmg
          wget -q $ONEAPI_INSTALLER_URL
          hdiutil attach -noverify -noautofsck $(basename $ONEAPI_INSTALLER_URL)
          sudo /Volumes/$(basename $ONEAPI_INSTALLER_URL .dmg)/bootstrapper.app/Contents/MacOS/bootstrapper --silent --eula accept --components intel.oneapi.mac.mkl.devel

          brew update
          brew install onednn

      - name: Build with cargo
        run: cargo build --verbose
